### ISSUE TITLE
How can you trace a method that does not change state?

### ISSUE THREAD

**Issue by roschler** [trufflesuite/truffle-debugger#76]
When working in the Truffle console using the debug command, how do you trace a contract method that does not change state?  Such methods don't generate a transaction ID, so there's nothing to feed the `debug` command.

**Comment by gnidan** [comment]
There's an issue for this already: #16. The reason this limitation exists is because there's only `debug_traceTransaction` in the RPC, and no `debug_traceCall`. There's a potential hack - which is to send the call as a transaction via web3 first, but I haven't pursued any real investigation as to what's involved / what's the risk of it not working well

**Comment by gnidan** [comment]
(Closing as duplicate)
